const userData = {
  "thesarrahgandhi@gmail.com": {
    name: "Sarrah Gandhi",
    role: "Student",
    image: "images/sarrah.jpg",
    lives: 5,
    points: 4500,
    printingBalance: 25.75,
    mealPlanBalance: 1250.5,
    notifications: [
      {
        title: "Attended the Ignite Concert",
        description: "10 points have been added to your account.",
        isRead: false,
      },
      {
        title: "New Event Available",
        description: "Check out the upcoming Wellness Workshop!",
        isRead: false,
      },
    ],
    expiryDate: "2024-06-01",
  },
  "n01638795@humber.ca": {
    name: "Deep Soni",
    role: "Student",
    image: "images/john.jpg",
    lives: 3,
    points: 3200,
    printingBalance: 50.0,
    mealPlanBalance: 975.25,
    notifications: [
      {
        title: "Ignite Concert",
        description: "You've earned 10 points!",
        isRead: false,
      },
      {
        title: "New Event",
        description: "Check out the upcoming Wellness Workshop!",
        isRead: false,
      },
    ],
    expiryDate: "2024-05-15",
  },
  "n12345678@humber.ca": {
    name: "Wendy Carmichael",
    role: "Student",
    image: "images/wendy.jpeg",
    lives: 4,
    points: 5200,
    printingBalance: 32.5,
    mealPlanBalance: 1875.0,
    notifications: [
      {
        title: "Achievement Unlocked",
        description: "You've earned the 'Early Bird' badge!",
        isRead: false,
      },
      {
        title: "Points Update",
        description: "15 points added for attending the workshop.",
        isRead: false,
      },
    ],
    expiryDate: "2024-07-01",
  },
  "michael.chen@gmail.com": {
    name: "Michael Chen",
    role: "Graduate Student",
    image: "images/michael.jpg",
    lives: 5,
    points: 6100,
    printingBalance: 65.25,
    mealPlanBalance: 2100.75,
    notifications: [
      {
        title: "Research Grant Opportunity",
        description: "New grant applications are now open.",
        isRead: false,
      },
    ],
    expiryDate: "2024-08-15",
  },
  "lisa.kumar@gmail.com": {
    name: "Lisa Kumar",
    role: "Student",
    image: "images/lisa.jpg",
    lives: 4,
    points: 3800,
    printingBalance: 18.9,
    mealPlanBalance: 850.25,
    notifications: [
      {
        title: "Event Registration Success",
        description: "You're registered for the Campus Festival!",
        isRead: false,
      },
      {
        title: "Points Milestone",
        description: "Congratulations! You've reached 3800 points!",
        isRead: false,
      },
    ],
    expiryDate: "2024-06-30",
  },
  "john.doe@example.com": {
    name: "John Doe",
    email: "john.doe@example.com",
    points: 2500,
    lives: 3,
    printingBalance: 15.5,
    mealPlanBalance: 750.0,
    image: "images/lisa.jpg",
    notifications: [
      {
        id: 1,
        message: "You earned 100 points!",
        read: false,
        timestamp: "2024-03-20T10:30:00",
      },
      {
        id: 2,
        message: "New challenge available",
        read: true,
        timestamp: "2024-03-19T15:45:00",
      },
    ],
    events: [
      {
        id: 1,
        title: "Team Challenge",
        date: "2024-03-25T14:00:00",
        description: "Join the team challenge to earn bonus points",
      },
    ],
  },
  "jane.smith@example.com": {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    points: 3200,
    lives: 4,
    printingBalance: 28.75,
    mealPlanBalance: 1450.5,
    image: "images/lisa.jpg",
    notifications: [
      {
        id: 1,
        message: "You completed a challenge!",
        read: false,
        timestamp: "2024-03-20T09:15:00",
      },
    ],
    events: [],
  },
  "test@example.com": {
    password: "password123",
    name: "John Doe",
    printingBalance: 10.25,
    mealPlanBalance: 500.25,
    image: "images/lisa.jpg",
    notifications: [
      {
        id: 1,
        message: "New message from Sarah",
        read: false,
        timestamp: "2024-03-20T10:30:00",
      },
      {
        id: 2,
        message: "Team meeting reminder",
        read: true,
        timestamp: "2024-03-20T09:15:00",
      },
      {
        id: 3,
        message: "Project deadline updated",
        read: false,
        timestamp: "2024-03-19T16:45:00",
      },
    ],
    events: [
      {
        id: 1,
        title: "Team Meeting",
        date: "2024-03-21T14:00:00",
        location: "Conference Room A",
      },
      {
        id: 2,
        title: "Project Review",
        date: "2024-03-22T10:00:00",
        location: "Virtual",
      },
    ],
  },
};
